NDefines.NGame.MAP_SCALE_PIXEL_TO_KM = 8.053
NDefines.NCountry.MIN_STABILITY = -1.0
NDefines.NCountry.MAX_STABILITY = 1.0
NDefines.NCountry.MIN_WAR_SUPPORT = -1.0
NDefines.NCountry.MAX_WAR_SUPPORT = 1.0
NDefines.NCountry.NUCLEAR_BOMB_DROP_WAR_SUPPORT_EFFECT_MAX_INFRA = 0
NDefines.NCountry.NUCLEAR_BOMB_DROP_WAR_SUPPORT_EFFECT_MAX_VP = 1000
NDefines.NMilitary.SLOWEST_SPEED = 2
NDefines.NMilitary.BASE_FEMALE_DIVISIONAL_COMMANDER_CHANCE = 0.5		--Chance to receive a female divisonal commander. This is set to zero in the base game, as we do not have generic female portraits for many graphical culture groups.
NDefines.NMilitary.NUKE_DELAY_HOURS = 0;