param(
    [string]$ModRoot = (Split-Path -Parent $PSScriptRoot),
    [string]$OutputPath = (Join-Path $PSScriptRoot 'roqualian_starting_state_and_vp_ids.txt')
)

$ErrorActionPreference = 'Stop'
$roqualianTags = @('ROQ', 'PER', 'TAK', 'LMB', 'RST', 'RSA', 'CRE') | Sort-Object -Unique

function Remove-PdxComments {
    param([string]$Text)
    return [regex]::Replace($Text, '(?m)#.*$', '')
}

$stateDirectory = Join-Path $ModRoot 'history\states'
$roqualianTagSet = [Collections.Generic.HashSet[string]]::new([StringComparer]::OrdinalIgnoreCase)
$roqualianTags | ForEach-Object { [void]$roqualianTagSet.Add($_) }

$records = foreach ($stateFile in Get-ChildItem -LiteralPath $stateDirectory -Filter '*.txt' -File) {
    $stateText = Remove-PdxComments ([IO.File]::ReadAllText($stateFile.FullName))
    $stateIdMatch = [regex]::Match($stateText, '(?m)^\s*id\s*=\s*(\d+)\s*$')
    if (-not $stateIdMatch.Success) {
        throw "No state ID found in '$($stateFile.FullName)'."
    }

    $owners = @([regex]::Matches($stateText, '(?m)^\s*owner\s*=\s*([A-Z0-9]{3})\s*$') |
        ForEach-Object { $_.Groups[1].Value } |
        Sort-Object -Unique)

    if ($owners.Count -gt 1) {
        throw "Conflicting undated owners in state $($stateIdMatch.Groups[1].Value): $($owners -join ', ')."
    }
    if ($owners.Count -eq 0 -or -not $roqualianTagSet.Contains($owners[0])) {
        continue
    }

    $victoryPointIds = @([regex]::Matches($stateText, 'victory_points\s*=\s*\{\s*(\d+)\s+[-+]?\d+(?:\.\d+)?') |
        ForEach-Object { [int]$_.Groups[1].Value } |
        Sort-Object -Unique)

    [pscustomobject]@{
        StateId = [int]$stateIdMatch.Groups[1].Value
        Owner = $owners[0]
        VictoryPointIds = @($victoryPointIds)
    }
}

$records = @($records | Sort-Object StateId)
$stateIds = @($records | ForEach-Object { $_.StateId })
$victoryPointIds = @($records | ForEach-Object { $_.VictoryPointIds } | Sort-Object -Unique)

$lines = [Collections.Generic.List[string]]::new()
$lines.Add('# Generated by scratch/list_roqualian_starting_states_and_vps.ps1')
$lines.Add("# Roqualian tags: $($roqualianTags.Count); states: $($stateIds.Count); victory-point provinces: $($victoryPointIds.Count)")
$lines.Add('')
$lines.Add("ROQUALIAN_TAGS = { $($roqualianTags -join ' ') }")
$lines.Add('')
$lines.Add("ROQUALIAN_STATE_IDS = { $($stateIds -join ' ') }")
$lines.Add('')
$lines.Add("ROQUALIAN_VP_PROVINCE_IDS = { $($victoryPointIds -join ' ') }")
$lines.Add('')
$lines.Add('# Per-state mapping: STATE_ID OWNER = { VP_PROVINCE_IDS }')
foreach ($record in $records) {
    $lines.Add("$($record.StateId) $($record.Owner) = { $($record.VictoryPointIds -join ' ') }")
}

[IO.File]::WriteAllLines($OutputPath, $lines, [Text.UTF8Encoding]::new($false))

Write-Output "Roqualian tags: $($roqualianTags.Count)"
Write-Output "State IDs: $($stateIds.Count)"
Write-Output "Victory-point province IDs: $($victoryPointIds.Count)"
Write-Output "Output: $OutputPath"
