param(
    [string]$ModRoot = (Split-Path -Parent $PSScriptRoot),
    [string]$OutputPath = (Join-Path $PSScriptRoot 'katzen_starting_state_and_vp_ids.txt')
)

$ErrorActionPreference = 'Stop'

function Remove-PdxComments {
    param([string]$Text)

    return [regex]::Replace($Text, '(?m)#.*$', '')
}

function Get-PdxNamedBlock {
    param(
        [string]$Text,
        [string]$Name
    )

    $match = [regex]::Match($Text, "(?m)^\s*$([regex]::Escape($Name))\s*=\s*\{")
    if (-not $match.Success) {
        throw "Could not find PDX block '$Name'."
    }

    $openingBrace = $Text.IndexOf('{', $match.Index)
    $depth = 0
    $inString = $false

    for ($index = $openingBrace; $index -lt $Text.Length; $index++) {
        $character = $Text[$index]
        if ($character -eq '"' -and ($index -eq 0 -or $Text[$index - 1] -ne '\')) {
            $inString = -not $inString
            continue
        }
        if ($inString) {
            continue
        }
        if ($character -eq '{') {
            $depth++
        }
        elseif ($character -eq '}') {
            $depth--
            if ($depth -eq 0) {
                return $Text.Substring($openingBrace + 1, $index - $openingBrace - 1)
            }
        }
    }

    throw "Block '$Name' has unbalanced braces."
}

$triggerPath = Join-Path $ModRoot 'common\scripted_triggers\LOK_advisor_setup_tag_triggers.txt'
$stateDirectory = Join-Path $ModRoot 'history\states'

$triggerText = Remove-PdxComments ([IO.File]::ReadAllText($triggerPath))
$speciesBlock = Get-PdxNamedBlock -Text $triggerText -Name 'tag_is_species_1'
$katzenTags = @([regex]::Matches($speciesBlock, '(?m)^\s*original_tag\s*=\s*([A-Z0-9]{3})\s*$') |
    ForEach-Object { $_.Groups[1].Value } |
    Sort-Object -Unique)

if ($katzenTags.Count -eq 0) {
    throw 'The Katzen scripted trigger contains no original_tag entries.'
}

$katzenTagSet = [Collections.Generic.HashSet[string]]::new([StringComparer]::OrdinalIgnoreCase)
$katzenTags | ForEach-Object { [void]$katzenTagSet.Add($_) }

$records = foreach ($stateFile in Get-ChildItem -LiteralPath $stateDirectory -Filter '*.txt' -File) {
    $stateText = Remove-PdxComments ([IO.File]::ReadAllText($stateFile.FullName))
    $stateIdMatch = [regex]::Match($stateText, '(?m)^\s*id\s*=\s*(\d+)\s*$')
    if (-not $stateIdMatch.Success) {
        throw "No state ID found in '$($stateFile.FullName)'."
    }

    $owners = @([regex]::Matches($stateText, '(?m)^\s*owner\s*=\s*([A-Z0-9]{3})\s*$') |
        ForEach-Object { $_.Groups[1].Value } |
        Sort-Object -Unique)

    if ($owners.Count -gt 1) {
        throw "Conflicting undated owners in state $($stateIdMatch.Groups[1].Value): $($owners -join ', ')."
    }
    if ($owners.Count -eq 0 -or -not $katzenTagSet.Contains($owners[0])) {
        continue
    }

    $victoryPointIds = @([regex]::Matches($stateText, 'victory_points\s*=\s*\{\s*(\d+)\s+[-+]?\d+(?:\.\d+)?') |
        ForEach-Object { [int]$_.Groups[1].Value } |
        Sort-Object -Unique)

    [pscustomobject]@{
        StateId = [int]$stateIdMatch.Groups[1].Value
        Owner = $owners[0]
        VictoryPointIds = @($victoryPointIds)
    }
}

$records = @($records | Sort-Object StateId)
$stateIds = @($records | ForEach-Object { $_.StateId })
$victoryPointIds = @($records | ForEach-Object { $_.VictoryPointIds } | Sort-Object -Unique)

$lines = [Collections.Generic.List[string]]::new()
$lines.Add('# Generated by scratch/list_katzen_starting_states_and_vps.ps1')
$lines.Add("# Katzen tags: $($katzenTags.Count); states: $($stateIds.Count); victory-point provinces: $($victoryPointIds.Count)")
$lines.Add('')
$lines.Add("KATZEN_TAGS = { $($katzenTags -join ' ') }")
$lines.Add('')
$lines.Add("KATZEN_STATE_IDS = { $($stateIds -join ' ') }")
$lines.Add('')
$lines.Add("KATZEN_VP_PROVINCE_IDS = { $($victoryPointIds -join ' ') }")
$lines.Add('')
$lines.Add('# Per-state mapping: STATE_ID OWNER = { VP_PROVINCE_IDS }')
foreach ($record in $records) {
    $lines.Add("$($record.StateId) $($record.Owner) = { $($record.VictoryPointIds -join ' ') }")
}

[IO.File]::WriteAllLines($OutputPath, $lines, [Text.UTF8Encoding]::new($false))

Write-Output "Katzen tags: $($katzenTags.Count)"
Write-Output "State IDs: $($stateIds.Count)"
Write-Output "Victory-point province IDs: $($victoryPointIds.Count)"
Write-Output "Output: $OutputPath"
