from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
IDEA_TAG = ROOT / "common/idea_tags/00_idea.txt"
HISTORY = ROOT / "history/countries"

BODY_IDS = {
    "parliament": "lok_legislative_parliament",
    "upper": "lok_legislative_upper_council",
    "direct": "lok_legislative_direct_democracy",
}
UPPER_IDEOLOGIES = {"authoritarian_democratic", "neutrality", "fascism"}


def patch_idea_tag():
    text = IDEA_TAG.read_text(encoding="utf-8-sig")
    if "slot = lok_legislative_body" not in text:
        anchor = "\t\tslot = economy\n"
        if anchor not in text:
            anchor = "        slot = economy\n"
        if anchor not in text:
            raise RuntimeError("Could not find government/economy slot in common/idea_tags/00_idea.txt")
        text = text.replace(anchor, anchor + anchor[:len(anchor)-len(anchor.lstrip())] + "slot = lok_legislative_body\n", 1)
    if "lok_legislative_body = civilian" not in text:
        m = re.search(r"(^\s*economy_laws\s*=\s*civilian\s*$)", text, flags=re.M)
        if not m:
            raise RuntimeError("Could not find economy_laws ledger entry")
        text = text[:m.end()] + "\n\tlok_legislative_body = civilian" + text[m.end():]
    IDEA_TAG.write_text(text, encoding="utf-8-sig")


def find_set_politics_end(text):
    m = re.search(r"\bset_politics\s*=\s*\{", text)
    if not m:
        return None
    brace = text.find("{", m.start())
    depth = 0
    for i in range(brace, len(text)):
        if text[i] == "{": depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                return i + 1
    return None


def body_for(path, text):
    tag = path.name.split(" - ", 1)[0].split("-",1)[0].strip().upper()
    if tag == "ROQ": return BODY_IDS["direct"]
    if tag == "MCF": return BODY_IDS["parliament"]
    m = re.search(r"\bruling_party\s*=\s*([A-Za-z0-9_]+)", text)
    ideology = m.group(1) if m else ""
    return BODY_IDS["upper"] if ideology in UPPER_IDEOLOGIES else BODY_IDS["parliament"]


def patch_history(path):
    text = path.read_text(encoding="utf-8-sig")
    # Idempotent: remove prior assignment generated by this patcher.
    text = re.sub(r"\n?\s*# Legislative Body Type\s*\n\s*add_ideas\s*=\s*lok_legislative_(?:parliament|upper_council|direct_democracy)\s*\n?", "\n", text)
    body = body_for(path, text)
    block = f"\n\n# Legislative Body Type\nadd_ideas = {body}\n"
    pos = find_set_politics_end(text)
    if pos is None:
        text = text.rstrip() + block
    else:
        text = text[:pos] + block + text[pos:]
    path.write_text(text, encoding="utf-8-sig")
    return body


def main():
    if not IDEA_TAG.exists() or not HISTORY.exists():
        raise SystemExit("Run this from the unpacked package inside the Legacy-of-Kattail mod root (tools/...).")
    patch_idea_tag()
    counts={v:0 for v in BODY_IDS.values()}
    files=sorted(HISTORY.glob("*.txt"))
    for p in files:
        b=patch_history(p); counts[b]+=1
    print(f"Patched common/idea_tags/00_idea.txt and {len(files)} country history files.")
    for k,v in counts.items(): print(f"  {k}: {v}")
    print("Special rules: ROQ = Direct Democracy; MCF = Parliament.")

if __name__ == "__main__": main()
